/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.84
 * Generated at: 2023-01-19 09:30:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ProductAdd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/admin.css\" />\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"http://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\">\n");
      out.write("<title>상품 등록</title>\n");
      out.write("<style>\n");
      out.write("* {\n");
      out.write("	margin: 0;\n");
      out.write("	padding: 0;\n");
      out.write("	box-sizing: border-box;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li {\n");
      out.write("	list-style: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("a {\n");
      out.write("	text-decoration: none !important;\n");
      out.write("	color: #fff !important;\n");
      out.write("}\n");
      out.write("\n");
      out.write("img {\n");
      out.write("	border: none;\n");
      out.write("	vertical-align: middle;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "admin.jsp", out, false);
      out.write("\n");
      out.write("	<div class=\"jumbotron\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<h1 class=\"display=3\">상품 등록</h1>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<div class=\"container\">\n");
      out.write("\n");
      out.write("		<form name=\"newProduct\" action=\"processAddProduct.jsp\"\n");
      out.write("			class=\"form-horizontal\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("\n");
      out.write("\n");
      out.write("			<div class=\"form-group row\">\n");
      out.write("				<label class=\"col-sm-2\">상품 목록 </label>\n");
      out.write("				<div class=\"com-sm-3\">\n");
      out.write("					<input type=\"text\" id=\"productId\" name=\"productId\"\n");
      out.write("						class=\"form-control\">\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"form-group row\">\n");
      out.write("				<label class=\"col-sm-2\">상품 이름</label>\n");
      out.write("				<div class=\"com-sm-3\">\n");
      out.write("					<input type=\"text\" id=\"name\" name=\"name\" class=\"form-control\">\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"form-group row\">\n");
      out.write("				<label class=\"col-sm-2\">가격</label>\n");
      out.write("				<div class=\"com-sm-3\">\n");
      out.write("					<input type=\"text\" id=\"unitPrice\" name=\"unitPrice\"\n");
      out.write("						class=\"form-control\">\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"form-group row\">\n");
      out.write("				<label class=\"col-sm-2\">상세 내용</label>\n");
      out.write("				<div class=\"com-sm-5\">\n");
      out.write("					<textarea name=\"description\" cols=\"50\" rows=\"2\"\n");
      out.write("						class=\"form-control\"></textarea>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"form-group row\">\n");
      out.write("				<label class=\"col-sm-2\">제조사</label>\n");
      out.write("				<div class=\"com-sm-3\">\n");
      out.write("					<input type=\"text\" name=\"manufacturer\" class=\"form-control\">\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"form-group row\">\n");
      out.write("				<label class=\"col-sm-2\">분류</label>\n");
      out.write("				<div class=\"com-sm-3\">\n");
      out.write("					<input type=\"text\" name=\"category\" class=\"form-control\">\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"form-group row\">\n");
      out.write("				<label class=\"col-sm-2\">재고 수</label>\n");
      out.write("				<div class=\"com-sm-3\">\n");
      out.write("					<input type=\"text\" id=\"unitsInStock\" name=\"unitsInStock\"\n");
      out.write("						class=\"form-control\">\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"form-group row\">\n");
      out.write("				<label class=\"col-sm-2\">상품 이미지</label>\n");
      out.write("				<div>\n");
      out.write("					<input type=\"file\" name=\"file\" class=\"form-control\">\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"form-group row\">\n");
      out.write("				<div class=\"col-sm-offset-2 col-sm-10\">\n");
      out.write("					<input type=\"submit\" class=\"btn btn-primary\" value=\"등록\">\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("		\n");
      out.write("		</form>\n");
      out.write("	</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
