/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.84
 * Generated at: 2023-01-18 01:52:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import java.util.ArrayList;
import yhj_java.user.*;

public final class admin_005fmember_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/admin/../footer.jsp", Long.valueOf(1673598735311L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("yhj_java.user");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>관리자페이지</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/header.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/footer.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/admin.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      yhj_java.user.User dao = null;
      dao = (yhj_java.user.User) _jspx_page_context.getAttribute("dao", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (dao == null){
        dao = new yhj_java.user.User();
        _jspx_page_context.setAttribute("dao", dao, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\n");
      out.write("\n");
      out.write("		<!-- header영역 -->\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../header.jsp", out, false);
      out.write("\n");
      out.write("	\n");
      out.write("	<header class=\"cs_func_page_header\">\n");
      out.write("		<h1 style=\"font-size: 2em;\">관리자페이지</h1>\n");
      out.write("		<div class=\"cs_category\">\n");
      out.write("			<a href=\"");
      out.print(request.getContextPath() );
      out.write("/admin/admin_member.jsp\">회원 관리</a>\n");
      out.write("			<a href=\"");
      out.print(request.getContextPath() );
      out.write("/admin.do?job=productSelect\">상품 관리</a>\n");
      out.write("			<a href=\"");
      out.print(request.getContextPath() );
      out.write("/admin/admin_sum.jsp\">매출 달력</a>\n");
      out.write("		</div>\n");
      out.write("</header>\n");
      out.write("	\n");
      out.write("<div class=\"admin-container\">\n");
      out.write("\n");
      out.write("\n");
      out.write("	<h2> 전체 회원 관리</h2>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<table class = \"admin-table\" style=\"width:100%\" >\n");
      out.write("\n");
      out.write("		<tr >\n");
      out.write("\n");
      out.write("			<th>아이디</th><th>회원명</th><th>이메일</th><th>전화</th><th>정보</th>\n");
      out.write("\n");
      out.write("		</tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- // 	ArrayList<MemberVo> list = dao.getMemberAll(); -->\n");
      out.write("\n");
      out.write("<!-- // 	for(MemberVo vo : list){ -->\n");
      out.write("\n");
      out.write("<!-- 			<tr> -->\n");
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("<!-- 			</tr> -->\n");
      out.write("\n");
      out.write("	</table>	\n");
      out.write("	<form action=\"member_modify_admin_form.jsp\" name=\"modifyFrm\" method=\"post\">\n");
      out.write("		<input type=\"hidden\" name=\"id\">\n");
      out.write("	</form>\n");
      out.write("</div>\n");
      out.write("		<div class = 'btns'>\n");
      out.write("		<input type = 'button' value = '<'/>\n");
      out.write("		<input type = 'button'class = 'num' value = '1'>\n");
      out.write("		<input type = 'button' value = '>'/>\n");
      out.write("	</div>\n");
      out.write("			\n");
      out.write("   <!-- footer영역 -->\n");
      out.write("   	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Footer</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/footer.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<br>\r\n");
      out.write("	<hr width=100% class=\"categoryhr\">\r\n");
      out.write("	<footer id=\"footer_footer\">\r\n");
      out.write("		<table width=80% align=\"center\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th width=\"30%\" align=\"left\" class=\"bottomtop\">마켓퀄리</th>\r\n");
      out.write("				<th width=\"30%\" align=\"left\" class=\"bottomtop\">고객센터</th>\r\n");
      out.write("				<th width=\"30%\" align=\"left\" class=\"bottomtop\">전자금융거래 분쟁처리</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<table>\r\n");
      out.write("						<tr align=\"left\">\r\n");
      out.write("							<td width=\"80%\" class=\"bottombt\">사업자등록번호 123-456-00000\r\n");
      out.write("								통신판매업신고번호 0000-신림-0123호 대표이사 윤희재 서울시 95, NAVER 0000, 12345 전화\r\n");
      out.write("								1588-0000 이메일 dbsgmlwo78@naver.com 사업자등록정보 확인\r\n");
      out.write("							<td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</table>\r\n");
      out.write("				</td>\r\n");
      out.write("				<td>\r\n");
      out.write("					<table>\r\n");
      out.write("						<tr align=\"left\">\r\n");
      out.write("							<td width=\"80%\" class=\"bottombt\">서울시 관악구 신림동 윤희재다 전화\r\n");
      out.write("								1588-0000 결제도용신고 1588-0000\r\n");
      out.write("							<td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</table>\r\n");
      out.write("				</td>\r\n");
      out.write("				<td>\r\n");
      out.write("					<table>\r\n");
      out.write("						<tr align=\"left\">\r\n");
      out.write("							<td width=\"80%\" class=\"bottombt\">전화 1589-0000\r\n");
      out.write("							<td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</table>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
